---
apiVersion: v1
kind: Namespace
metadata:
  name: production-app

---
# Persistent Volume Claim for MySQL data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: production-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
# MySQL Deployment with persistent storage
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: production-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rootpassword123"
        - name: MYSQL_DATABASE
          value: "myappdb"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc

---
# MySQL Service
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: production-app
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306

---
# Nginx Deployment (stateless)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: production-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80

---
# Nginx Service
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: production-app
  labels:
    app: nginx
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
